mpi:
  - mpich
  - openmpi

scalar:
  - real
  - complex

hdf5:
  - 1.10.6
  - 1.10.6=mpi*

pin_run_as_build:
  hypre:
    max_pin: x.x.x
  metis:
    max_pin: x.x
  parmetis:
    max_pin: x.x
  scalapack:
    max_pin: x.x
  suitesparse:
    max_pin: x.x  # [not osx]
    max_pin: x.x.x  # [osx]