{% set version = "3.9.0" %}
{% set sha256 = 'a233e0d7f69c98504a1c3548162c6024f7797dde5556b83b0f98ce7326251ca1' %}
{% set blas = os.environ.get('BLAS') or 'openblas' %}
{% set mpi = os.environ.get('MPI') or 'mpich' %}
{% set req = {'mpich':'>=3.2', 'openmpi':'>=1.10'} %}

package:
  name: petsc
  version: {{version}}

source:
  fn: petsc-{{version}}.tar.gz
  url: http://ftp.mcs.anl.gov/pub/petsc/release-snapshots/petsc-lite-{{version}}.tar.gz
  sha256: {{sha256}}

build:
  skip: true  # [win]
  number: 0
  binary_relocation: true
  detect_binary_files_with_prefix: true
  features:
    - blas_{{blas}}

requirements:
  build:
    - gcc  # [not win]
    - toolchain
    - python 2.7.*
    - cmake
    - blas 1.* {{blas}}
    {% if blas == 'openblas' %}
    - openblas 0.2.20|0.2.20.*
    {% endif %}
    - {{mpi}} {{req[mpi]}}
    - hypre 2.11.2
    - metis 5.1.0
    - mumps-mpi 5.0.2
    - parmetis 4.0.3
    - ptscotch 6.0.4
    - scalapack 2.0.2
    - suitesparse 4.5.4
  run:
    - libgcc  # [linux]
    - libgfortran  # [osx]
    - blas 1.* {{blas}}
    {% if blas == 'openblas' %}
    - openblas 0.2.20|0.2.20.*
    {% endif %}
    - {{mpi}} {{req[mpi]}}
    - hypre 2.11.2
    - metis 5.1.0
    - mumps-mpi 5.0.2
    - parmetis 4.0.3
    - ptscotch 6.0.4
    - scalapack 2.0.2
    - suitesparse 4.5.4

test:
  requires:
    - gcc  # [not win]
  source_files:
    - src/snes/examples/tests
  commands:
    - conda inspect linkages petsc  # [not win]

about:
  home: http://www.mcs.anl.gov/petsc/
  summary: 'PETSc: Portable, Extensible Toolkit for Scientific Computation'
  license: BSD 2-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - dalcinl
    - minrk
