{% set version = "3.14.5" %}
{% set sha256 = "8b8ff5c4e10468f696803b354a502d690c7d25c19d694a7e10008a302fdbb048" %}

{% set mpi = mpi or 'mpich' %}

package:
  name: petsc
  version: {{ version }}

source:
  fn: petsc-{{ version }}.tar.gz
  url: http://ftp.mcs.anl.gov/pub/petsc/release-snapshots/petsc-lite-{{ version }}.tar.gz
  sha256: {{ sha256 }}
  patches:
    - ignore-not-invalid.patch
    - no-cppflags-in-pkgconfig-cflags.patch

build:
  skip: true  # [win]
  number: 1
  run_exports:
    - {{ pin_subpackage('petsc', max_pin='x.x') }}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ compiler('fortran') }}
    - make
    - pkg-config
    - python
  host:
    - blas-devel
    - libblas
    - libcblas
    - liblapack
    - cmake
    - {{ mpi }}
    - hypre
    - metis
    - parmetis
    - ptscotch
    - scalapack
    - superlu
{% if mpi == "mpich" %}
    - superlu_dist
{% endif %}
    - scotch
    - mumps-mpi
    - suitesparse
    - hdf5
  run:
    - blas-devel
    - {{ mpi }}
    - hypre
    - metis
    - parmetis
    - ptscotch
    - scalapack
    - superlu
{% if mpi == "mpich" %}
    - superlu_dist
{% endif %}
    - scotch
    - mumps-mpi
    - suitesparse
    - hdf5

test:
  requires:
    - pkg-config
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ compiler('fortran') }}
    - make
  files:
    - tests/ex1.c
    - tests/ex1f.F90
    - tests/makefile
  commands:
    - pkg-config --validate PETSc
    - pkg-config --cflags PETSc
    - pkg-config --libs PETSc

about:
  home: http://www.mcs.anl.gov/petsc/
  summary: 'PETSc: Portable, Extensible Toolkit for Scientific Computation'
  license: BSD-2-Clause
  license_file: LICENSE
  license_family: BSD

extra:
  recipe-maintainers:
    - dalcinl
    - minrk
    - davidbrochart
    - SylvainCorlay
    - martinRenou
