{% set build = 1 %}
{% set version = '3.8.3' %}
{% set sha256 = '5509e35d55d5ce9e92dbe7a83f5e509865aea2a4cc2d9f16f72b7a5ceaafed96' %}
{% set blas = os.environ.get('BLAS') or 'openblas' %}
{% set openblas_version = '0.2.20|0.2.20.*' %}
{% set mpi = os.environ.get('MPI') or 'mpich' %}
{% set req = {'mpich':'>=3.2', 'openmpi':'>=1.10'} %}

package:
  name: petsc
  version: {{version}}

source:
  fn: petsc-{{version}}.tar.gz
  url: http://ftp.mcs.anl.gov/pub/petsc/release-snapshots/petsc-lite-{{version}}.tar.gz
  sha256: {{sha256}}
  patches:
    - petsc-lib.patch

build:
  skip: true  # [win]
  number: {{build}}
  binary_relocation: true
  detect_binary_files_with_prefix: true
  features:
    - blas_{{blas}}

requirements:
  build:
    - gcc  # [not win]
    - toolchain
    - python 2.7.*
    - cmake
    - blas 1.* {{blas}}
    {% if blas == 'openblas' %}
    - openblas {{openblas_version}}
    {% endif %}
    - {{mpi}} {{req[mpi]}}
    - ptscotch
    - suitesparse 4.5.4
  run:
    - libgcc  # [linux]
    - libgfortran  # [osx]
    - blas 1.* {{blas}}
    {% if blas == 'openblas' %}
    - openblas {{openblas_version}}
    {% endif %}
    - {{mpi}} {{req[mpi]}}
    - ptscotch
    - suitesparse 4.5.4

test:
  requires:
    - gcc  # [not win]
  source_files:
    - src/snes/examples/tests
  commands:
    - conda inspect linkages petsc  # [not win]

about:
  home: http://www.mcs.anl.gov/petsc/
  summary: 'PETSc: Portable, Extensible Toolkit for Scientific Computation'
  license: BSD 2-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - dalcinl
    - minrk
