{% set version = "3.22.1" %}
{% set build = 0 %}

{% set mpi = mpi or 'mpich' %}
{% if scalar == "real" %}
{% set build = build + 100 %}
{% endif %}

{% set cuda_target_name = "x86_64-linux" %}  # [linux64]
{% set cuda_target_name = "ppc64le-linux" %}  # [ppc64le]
{% set cuda_target_name = "sbsa-linux" %}  # [aarch64]
{% set cuda_target_name = "" %}  # [osx or win]

{% if cuda_compiler_version == "None" %}
{% set cuda_major = 0 %}
{% else %}
{% set cuda_major = environ.get("cuda_compiler_version", "11.8").split(".")[0] | int %}
{% endif %}

package:
  name: petsc
  version: {{ version }}

source:
  url: https://web.cels.anl.gov/projects/petsc/download/release-snapshots/petsc-{{ version }}.tar.gz
  sha256: 7117d3ae6827f681ed9737939d4e86896b4751e27cca941bb07e5703f19a0a7b
  patches:
    - ignore-not-invalid.patch
    - no-cppflags-in-pkgconfig-cflags.patch
    - target-cudadir.patch
    - mr7912.patch

build:
  skip: true  # [win]
  skip: true  # [cuda_compiler_version not in ("None", "11.8", "12.4")]
  number: {{ build }}
  string: {{ scalar }}_h{{ PKG_HASH }}_{{ build }}  # [cuda_compiler_version == "None"]
  string: cuda{{ cuda_major }}_{{ scalar }}_h{{ PKG_HASH }}_{{ build }}  # [cuda_compiler_version != "None"]
  script_env:
    - CUDA_CONDA_TARGET_NAME={{ cuda_target_name }}
  run_exports:
    - {{ pin_subpackage('petsc', max_pin='x.x') }}
    - petsc * {{ scalar }}_*                       # [cuda_compiler_version == "None"]
    - petsc * cuda{{ cuda_major }}_{{ scalar }}_*  # [cuda_compiler_version != "None"]
  track_features:
    - petsc_complex  # [scalar == "complex"]
    - petsc_cuda  # [cuda_compiler_version != "None"]
  # Allow using 11.2 with 11.8 or 12.x with 12.4
  ignore_run_exports_from:
    - {{ compiler('cuda') }}  # [cuda_compiler_version != "None"]
    - cudatoolkit             # [(cuda_compiler_version or "").startswith("11")]
    {% if cuda_major >= 12 %}
    - cuda-cudart-dev
    - cuda-nvtx-dev
    - libcublas-dev
    - libcufft-dev
    - libcurand-dev
    - libcusolver-dev
    - libcusparse-dev
    {% endif %}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
    - {{ compiler('cxx') }}
    - {{ compiler('fortran') }}
    - {{ compiler('cuda') }}  # [cuda_compiler_version != "None"]
    - make
    - pkg-config
    - python
    - gnuconfig   # [unix]
    - {{ mpi }}  # [mpi == 'openmpi' and build_platform != target_platform]
  host:
    - libblas
    - libcblas
    - liblapack
    - cmake
    - {{ mpi }}
    - yaml
    - hypre
    - metis
    - parmetis
    - libptscotch
    - scalapack
    - superlu
    - superlu_dist
    - libscotch
    - mumps-mpi
    - suitesparse
    - hdf5
    - hdf5 * mpi_{{ mpi }}_*
    - fftw * mpi_{{ mpi }}_*
    - cuda-version {{ cuda_compiler_version }}  # [cuda_compiler_version != "None"]
    - cudatoolkit                               # [(cuda_compiler_version or "").startswith("11")]
    {% if cuda_major >= 12 %}
    - cuda-cudart-dev
    - cuda-nvtx-dev
    - libcublas-dev
    - libcufft-dev
    - libcurand-dev
    - libcusolver-dev
    - libcusparse-dev
    {% endif %}
  run:
    - {{ mpi }}
    - yaml
    - hypre
    - metis
    - parmetis
    - libptscotch
    - scalapack
    - superlu
    - superlu_dist
    - libscotch
    - mumps-mpi
    - suitesparse
    - hdf5
    - hdf5 * mpi_{{ mpi }}_*
    - fftw * mpi_{{ mpi }}_*
    - cuda-version >={{ cuda_major }}.2,<{{ cuda_major+1 }}  # [(cuda_compiler_version or "").startswith("11")]
    - cudatoolkit >={{ cuda_major }}.2,<{{ cuda_major+1 }}   # [(cuda_compiler_version or "").startswith("11")]
    {% if cuda_major >= 12 %}
    - cuda-version >={{ cuda_major }}.0,<{{ cuda_major+1 }}
    - cuda-cudart
    - cuda-nvtx
    - libcublas
    - libcufft
    - libcurand
    - libcusolver
    - libcusparse
    - {{ pin_compatible('cuda-nvtx', min_pin='x', max_pin='x') }}
    - {{ pin_compatible('cuda-cudart', min_pin='x', max_pin='x') }}
    - {{ pin_compatible('libcublas', min_pin='x', max_pin='x') }}
    - {{ pin_compatible('libcufft', min_pin='x', max_pin='x') }}
    - {{ pin_compatible('libcurand', min_pin='x', max_pin='x') }}
    - {{ pin_compatible('libcusolver', min_pin='x', max_pin='x') }}
    - {{ pin_compatible('libcusparse', min_pin='x', max_pin='x') }}
    {% endif %}

test:
  requires:
    - pkg-config
    - make
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ compiler('fortran') }}
  files:
    - tests/ex1.c
    - tests/ex1f.F90
    - tests/testdlopen.c
    - tests/makefile
  commands:
    - pkg-config --validate PETSc
    - pkg-config --cflags PETSc
    - pkg-config --libs PETSc

about:
  home: https://www.mcs.anl.gov/petsc/
  summary: 'PETSc: Portable, Extensible Toolkit for Scientific Computation'
  license: BSD-2-Clause
  license_file: LICENSE
  license_family: BSD
  dev_url: https://gitlab.com/petsc/petsc
  doc_url: https://petsc.org/release/docs/manual/

extra:
  recipe-maintainers:
    - jan-janssen
    - dalcinl
    - minrk
    - davidbrochart
    - SylvainCorlay
    - martinRenou
    - matthiasdiener
    - stefanozampini
