{% set version = "3.21.0" %}
{% set build = 0 %}

{% set mpi = mpi or 'mpich' %}
{% if scalar == "real" %}
{% set build = build + 100 %}
{% endif %}

package:
  name: petsc
  version: {{ version }}

source:
  url: https://web.cels.anl.gov/projects/petsc/download/release-snapshots/petsc-{{ version }}.tar.gz
  sha256: 1e0c2f92514c72f80d4a4d0e6439a3aba0ceda7a0bcbc7ad9c44ce4cd8b14c28
  patches:
    - ignore-not-invalid.patch
    - no-cppflags-in-pkgconfig-cflags.patch

build:
  skip: true  # [win]
  number: {{ build }}
  string: {{ scalar }}_h{{ PKG_HASH }}_{{ build }}
  run_exports:
    - {{ pin_subpackage('petsc', max_pin='x.x') }}
    - petsc * {{ scalar }}_*
  track_features:
    - petsc_complex  # [scalar == "complex"]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ compiler('fortran') }}
    - make
    - pkg-config
    - python
    - gnuconfig   # [unix]
    - {{ mpi }}  # [mpi == 'openmpi' and build_platform != target_platform]
  host:
    - libblas
    - libcblas
    - liblapack
    - cmake
    - {{ mpi }}
    - yaml
    # FIXME: unpin hypre after next petsc release
    - hypre 2.28
    - metis
    - parmetis
    - libptscotch
    - scalapack
    - superlu
    - superlu_dist
    - libscotch
    - mumps-mpi
    - suitesparse
    - hdf5
    - hdf5 * mpi_{{ mpi }}_*
    - fftw * mpi_{{ mpi }}_*
  run:
    - {{ mpi }}
    - yaml
    - hypre
    - metis
    - parmetis
    - libptscotch
    - scalapack
    - superlu
    - superlu_dist
    - libscotch
    - mumps-mpi
    - suitesparse
    - hdf5
    - hdf5 * mpi_{{ mpi }}_*
    - fftw * mpi_{{ mpi }}_*

test:
  requires:
    - pkg-config
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ compiler('fortran') }}
    - make
  files:
    - tests/ex1.c
    - tests/ex1f.F90
    - tests/makefile
  commands:
    - pkg-config --validate PETSc
    - pkg-config --cflags PETSc
    - pkg-config --libs PETSc

about:
  home: https://www.mcs.anl.gov/petsc/
  summary: 'PETSc: Portable, Extensible Toolkit for Scientific Computation'
  license: BSD-2-Clause
  license_file: LICENSE
  license_family: BSD
  dev_url: https://gitlab.com/petsc/petsc
  doc_url: https://petsc.org/release/docs/manual/

extra:
  recipe-maintainers:
    - jan-janssen
    - dalcinl
    - minrk
    - davidbrochart
    - SylvainCorlay
    - martinRenou
    - matthiasdiener
