{% set version = "3.15.3" %}
{% set sha256 = "483028088020001e6f8d57b78a7fc880ed52d6693f57d627779c428f55cff73d" %}
{% set build = 1 %}

{% set mpi = mpi or 'mpich' %}
{% if scalar == "real" %}
{% set build = build + 100 %}
{% endif %}

package:
  name: petsc
  version: {{ version }}

source:
  fn: petsc-{{ version }}.tar.gz
  url: http://ftp.mcs.anl.gov/pub/petsc/release-snapshots/petsc-lite-{{ version }}.tar.gz
  sha256: {{ sha256 }}
  patches:
    - ignore-not-invalid.patch
    - no-cppflags-in-pkgconfig-cflags.patch

build:
  skip: true  # [win]
  number: {{ build }}
  string: {{ scalar }}_h{{ PKG_HASH }}_{{ build }}
  run_exports:
    - {{ pin_subpackage('petsc', max_pin='x.x') }}
  track_features:
    - petsc_complex  # [scalar == "complex"]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ compiler('fortran') }}
    - make
    - pkg-config
    - python
  host:
    - libblas
    - libcblas
    - liblapack
    - cmake
    - {{ mpi }}
    - yaml
    - hypre
    - metis
    - parmetis
    - ptscotch
    - scalapack
    - superlu
{% if mpi == "mpich" %}
    - superlu_dist
{% endif %}
    - scotch
    - mumps-mpi
    - suitesparse
    - hdf5
    - fftw * mpi_{{ mpi }}_*
  run:
    - {{ mpi }}
    - yaml
    - hypre
    - metis
    - parmetis
    - ptscotch
    - scalapack
    - superlu
{% if mpi == "mpich" %}
    - superlu_dist
{% endif %}
    - scotch
    - mumps-mpi
    - suitesparse
    - hdf5
    - fftw * mpi_{{ mpi }}_*

test:
  requires:
    - pkg-config
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ compiler('fortran') }}
    - make
  files:
    - tests/ex1.c
    - tests/ex1f.F90
    - tests/makefile
  commands:
    - pkg-config --validate PETSc
    - pkg-config --cflags PETSc
    - pkg-config --libs PETSc

about:
  home: http://www.mcs.anl.gov/petsc/
  summary: 'PETSc: Portable, Extensible Toolkit for Scientific Computation'
  license: BSD-2-Clause
  license_file: LICENSE
  license_family: BSD

extra:
  recipe-maintainers:
    - dalcinl
    - minrk
    - davidbrochart
    - SylvainCorlay
    - martinRenou
