{% set version = "3.10.1" %}
{% set sha256 = "61265950e43e77cf950070a2422a2f140f2ca371f8bfec265ffcaed84c934f84" %}

package:
  name: petsc
  version: {{ version }}

source:
  fn: petsc-{{ version }}.tar.gz
  url: http://ftp.mcs.anl.gov/pub/petsc/release-snapshots/petsc-lite-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  skip: true  # [win]
  number: 0
  # we didn't need to add this feature,
  # but we cannot remove it until blas mpkg drops track_features
  features:
    - blas_openblas
  run_exports:
    - {{ pin_subpackage('petsc', max_pin='x.x')}}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ compiler('fortran') }}
    - python 2.7.*
  host:
    - cmake
    - openblas
    - {{ mpi }}
    - hypre
    - metis
    - parmetis
    - ptscotch
    - scalapack
    - mumps-mpi
    - suitesparse
  run:
    - openblas
    - {{ mpi }}
    - hypre
    - metis
    - parmetis
    - ptscotch
    - scalapack
    - mumps-mpi
    - suitesparse

test:
  requires:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ compiler('fortran') }}
  files:
    - tests/ex1.c
    - tests/ex1f.F90
    - tests/makefile
  commands:
    - conda inspect objects  petsc  # [osx]
    - conda inspect linkages petsc  # [not win]

about:
  home: http://www.mcs.anl.gov/petsc/
  summary: 'PETSc: Portable, Extensible Toolkit for Scientific Computation'
  license: BSD 2-Clause
  license_file: LICENSE
  license_family: BSD

extra:
  recipe-maintainers:
    - dalcinl
    - minrk
