schema_version: 1

context:
  name: petsc
  version: "3.24.3"
  build: 1
  # these variables should all be overridden in variant files
  # but default values are sometimes needed for conda-smithy rerender
  mpi: ${{ mpi | default('mpich') }}
  scalar: ${{ scalar | default('real') }}
  cuda_compiler_version: ${{ cuda_compiler_version | default('None') }}
  # construct some variables to use in the recipe
  # with_cuda can be used as a bool for cuda or not conditions
  with_cuda: ${{ 'true' if cuda_compiler_version != 'None' else '' }}
  # cuda_major is always the major version of cuda as an integer string ('0' if not with_cuda)
  cuda_major: >-
    ${{
      cuda_compiler_version | split('.') | first
      if with_cuda
      else "0"
    }}
  # construct the build prefix (e.g. 'cuda12_complex' or 'real')
  cuda_prefix: ${{ "cuda" + cuda_major + "_" }}
  build_prefix: ${{ cuda_prefix + scalar if with_cuda else scalar }}

package:
  name: petsc
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/${{ name }}-${{ version }}.tar.gz
  sha256: dde6f6ef2c5ef8c473a831d56a2e3192b5304c50c4cc5ded7f296ef6d86aaf13
  patches:
    - ignore-not-invalid.patch
    - no-cppflags-in-pkgconfig-cflags.patch
    - target-cudadir.patch
    - fix-demangle.patch

build:
  number: ${{ build }}
  string: ${{ build_prefix }}_h${{ hash }}_${{ build }}
  skip: win
  variant:
    # deprioritize cuda and complex with track_features
    down_prioritize_variant: >
      ${{
        (1 if with_cuda else 0)
      + (1 if scalar == "complex" else 0)
      }}

requirements:
  build:
    - ${{ compiler('c') }}
    - ${{ stdlib('c') }}
    - ${{ compiler('cxx') }}
    - ${{ compiler('fortran') }}
    - if: with_cuda
      then: ${{ compiler('cuda') }}
    - if: osx
      then:
        # has symlinks for 'otool', 'install_name_tool', etc.
        # otherwise, we only have 'arm64-apple-darwin20.0.0-install_name_tool'
        - cctools
    - bison  # not actually required, but petsc declares it as necessary to link against ptscotch
    - diffutils
    - make
    - pkg-config
    - python 3.12.*
    - gnuconfig
    - if: mpi == 'openmpi' and build_platform != target_platform
      then: ${{ mpi }}
  host:
    - libblas
    - liblapack
    - cmake
    - ${{ mpi }}
    - yaml
    - if: scalar == 'real'
      then:
        - hypre
    - libhwloc
    - metis
    - parmetis
    - libptscotch
    - scalapack
    - superlu
    - superlu_dist
    - libscotch
    # needs 32b libscotch
    - libscotch * int32_*
    - mumps-mpi
    # suitesparse
    - libamd
    - libcholmod
    - libklu
    - libspqr
    - libumfpack

    - hdf5
    - hdf5 * mpi_${{ mpi }}_*
    - fftw
    - fftw * mpi_${{ mpi }}_*

    # cuda
    - if: with_cuda
      then:
        - cuda-version ${{ cuda_compiler_version }}.*
        - cuda-cudart-dev
        - cuda-nvtx-dev
        - libcublas-dev
        - libcufft-dev
        - libcurand-dev
        - libcusolver-dev
        - libcusparse-dev
  run:
    - if: with_cuda
      then:
        - ${{ pin_compatible('cuda-version', lower_bound='x', upper_bound='x') }}
        - ${{ pin_compatible('cuda-nvtx', lower_bound='x', upper_bound='x') }}
        - ${{ pin_compatible('cuda-cudart', lower_bound='x', upper_bound='x') }}
        - ${{ pin_compatible('libcublas', lower_bound='x', upper_bound='x') }}
        - ${{ pin_compatible('libcufft', lower_bound='x', upper_bound='x') }}
        - ${{ pin_compatible('libcurand', lower_bound='x', upper_bound='x') }}
        - ${{ pin_compatible('libcusolver', lower_bound='x', upper_bound='x') }}
        - ${{ pin_compatible('libcusparse', lower_bound='x', upper_bound='x') }}
  run_exports:
    weak:
      - ${{ pin_subpackage('petsc', upper_bound='x.x') }}
      - petsc * ${{ build_prefix }}_*
  ignore_run_exports:
    from_package:
      - if: with_cuda
        then:
          - ${{ compiler("cuda") | split | first }}
      - cudatoolkit
      - cuda-cudart-dev
      - cuda-nvtx-dev
      - libcublas-dev
      - libcufft-dev
      - libcurand-dev
      - libcusolver-dev
      - libcusparse-dev

tests:
  - files:
      recipe:
        - tests/ex1.c
        - tests/ex1f.F90
        - tests/testdlopen.c
        - tests/makefile
    requirements:
      run:
        - pkg-config
        - make
        - ${{ compiler('c') }}
        - ${{ compiler('cxx') }}
        - ${{ compiler('fortran') }}
    script:
      file: run_test.sh
      env:
        target_platform: ${{ target_platform }}
        cuda_compiler_version: ${{ cuda_compiler_version }}

about:
  summary: |
    PETSc: Portable, Extensible Toolkit for Scientific Computation
  license: BSD-2-Clause
  license_file: LICENSE
  homepage: https://petsc.org/
  repository: https://gitlab.com/petsc/petsc
  documentation: https://petsc.org/release/docs/manual/

extra:
  recipe-maintainers:
    - jan-janssen
    - dalcinl
    - minrk
    - davidbrochart
    - SylvainCorlay
    - martinRenou
    - matthiasdiener
    - stefanozampini
