matrix:
  - [[MPI_VARIANT, 'mpich']]
  - [[MPI_VARIANT, 'openmpi']]
travis:
  secure:
    BINSTAR_TOKEN: ag/1uLBYhfsHOQm4tkeItGKEgKFnWswY5xISNzrOSGp/8lOJxgAFJGz32E/fTTWS04R0nXBXHt38sSU+PcRVJ2MinXH4fOND4BB5UzxOLM/zApPtCpCr4CKvUDO25sLCNFnJu9yM7kCb/8gdxGzaIqN7yZ84CP7MlfW7aTmjEfpehQIk3wJCEDWoztMiQWBrwld1W85Yo7QeDOlizW56fQAGwLWRW16x9vNh/QQSO+jJUYUvyKCWCA03tsmH9VszvJuSKLehk73C4rkyqQ2Rs4eU6TgWubDYggWYIkOl/ErDMAl+ckayBf2FQiApegHelq7l/2lhH5TUqmNZvXSHoQQCI4gLxU60WnwfpCgs8yiUcxaHs1iyftQW4offs4TlIaw/RbiH9xnMXWDXealcVF5CMF5eeFd5/e+0I9nhmqiEK+K7fa6CIUSOTehwXlneIK6f0//zYfZ62QfbffuYByJ24YTlwEIa4uxkuUlJt8tMBRp6nvyxXh5gCf0jV3M6YEona0tUhbQSmK7OpehORsCLdUC8+HjjbBZ0+mLFeT4IVuQTCEFrBsDd3Xrx6RFp+ngDULuIZxGtFitF8hy7AuE+pchvza5gweNsKUkAIHPYQKAr2SgGmv5eFqbk+bkoNW6e3deMvwZ/gXXhNvlEqUt8eSq2uGd3LLKhkkiaW8c=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
