version: 2

jobs:
  build__MPI_VARIANT_mpich:
    working_directory: ~/test
    machine: true
    environment:
      - MPI_VARIANT: "mpich"
    steps:
      - checkout
      - run:
          name: Fast finish outdated PRs and merge PRs
          command: |
            ./ci_support/fast_finish_ci_pr_build.sh
            ./ci_support/checkout_merge_commit.sh
      - run:
          command: docker pull condaforge/linux-anvil
      - run:
          name: Print conda-build environment variables
          command: |
            echo "MPI_VARIANT=${MPI_VARIANT}"
      - run:
          # Run, test and (if we have a BINSTAR_TOKEN) upload the distributions.
          command: ./ci_support/run_docker_build.sh
  build__MPI_VARIANT_openmpi:
    working_directory: ~/test
    machine: true
    environment:
      - MPI_VARIANT: "openmpi"
    steps:
      - checkout
      - run:
          name: Fast finish outdated PRs and merge PRs
          command: |
            ./ci_support/fast_finish_ci_pr_build.sh
            ./ci_support/checkout_merge_commit.sh
      - run:
          command: docker pull condaforge/linux-anvil
      - run:
          name: Print conda-build environment variables
          command: |
            echo "MPI_VARIANT=${MPI_VARIANT}"
      - run:
          # Run, test and (if we have a BINSTAR_TOKEN) upload the distributions.
          command: ./ci_support/run_docker_build.sh

workflows:
  version: 2
  build_and_test:
    jobs:
      - build__MPI_VARIANT_mpich
      - build__MPI_VARIANT_openmpi
