# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.
# -*- mode: yaml -*-

jobs:
- job: linux
  pool:
    vmImage: ubuntu-latest
  strategy:
    matrix:
      linux_64_c_stdlib_version2.17cuda_compiler_version12.9mpimpichscalarcomplex:
        CONFIG: linux_64_c_stdlib_version2.17cuda_compiler_version12.9mpimpichscalarcomplex
        UPLOAD_PACKAGES: 'True'
        DOCKER_IMAGE: quay.io/condaforge/linux-anvil-x86_64:alma9
      linux_64_c_stdlib_version2.17cuda_compiler_version12.9mpimpichscalarreal:
        CONFIG: linux_64_c_stdlib_version2.17cuda_compiler_version12.9mpimpichscalarreal
        UPLOAD_PACKAGES: 'True'
        DOCKER_IMAGE: quay.io/condaforge/linux-anvil-x86_64:alma9
      linux_64_c_stdlib_version2.17cuda_compiler_version12.9mpiopenmpiscalarcomplex:
        CONFIG: linux_64_c_stdlib_version2.17cuda_compiler_version12.9mpiopenmpiscalarcomplex
        UPLOAD_PACKAGES: 'True'
        DOCKER_IMAGE: quay.io/condaforge/linux-anvil-x86_64:alma9
      linux_64_c_stdlib_version2.17cuda_compiler_version12.9mpiopenmpiscalarreal:
        CONFIG: linux_64_c_stdlib_version2.17cuda_compiler_version12.9mpiopenmpiscalarreal
        UPLOAD_PACKAGES: 'True'
        DOCKER_IMAGE: quay.io/condaforge/linux-anvil-x86_64:alma9
      linux_64_c_stdlib_version2.17cuda_compiler_versionNonempimpichscalarcomplex:
        CONFIG: linux_64_c_stdlib_version2.17cuda_compiler_versionNonempimpichscalarcomplex
        UPLOAD_PACKAGES: 'True'
        DOCKER_IMAGE: quay.io/condaforge/linux-anvil-x86_64:alma9
      linux_64_c_stdlib_version2.17cuda_compiler_versionNonempimpichscalarreal:
        CONFIG: linux_64_c_stdlib_version2.17cuda_compiler_versionNonempimpichscalarreal
        UPLOAD_PACKAGES: 'True'
        DOCKER_IMAGE: quay.io/condaforge/linux-anvil-x86_64:alma9
      linux_64_c_stdlib_version2.17cuda_compiler_versionNonempiopenmpiscalarcomplex:
        CONFIG: linux_64_c_stdlib_version2.17cuda_compiler_versionNonempiopenmpiscalarcomplex
        UPLOAD_PACKAGES: 'True'
        DOCKER_IMAGE: quay.io/condaforge/linux-anvil-x86_64:alma9
      linux_64_c_stdlib_version2.17cuda_compiler_versionNonempiopenmpiscalarreal:
        CONFIG: linux_64_c_stdlib_version2.17cuda_compiler_versionNonempiopenmpiscalarreal
        UPLOAD_PACKAGES: 'True'
        DOCKER_IMAGE: quay.io/condaforge/linux-anvil-x86_64:alma9
      linux_64_c_stdlib_version2.28cuda_compiler_version13.0mpimpichscalarcomplex:
        CONFIG: linux_64_c_stdlib_version2.28cuda_compiler_version13.0mpimpichscalarcomplex
        UPLOAD_PACKAGES: 'True'
        DOCKER_IMAGE: quay.io/condaforge/linux-anvil-x86_64:alma9
      linux_64_c_stdlib_version2.28cuda_compiler_version13.0mpimpichscalarreal:
        CONFIG: linux_64_c_stdlib_version2.28cuda_compiler_version13.0mpimpichscalarreal
        UPLOAD_PACKAGES: 'True'
        DOCKER_IMAGE: quay.io/condaforge/linux-anvil-x86_64:alma9
      linux_64_c_stdlib_version2.28cuda_compiler_version13.0mpiopenmpiscalarcomplex:
        CONFIG: linux_64_c_stdlib_version2.28cuda_compiler_version13.0mpiopenmpiscalarcomplex
        UPLOAD_PACKAGES: 'True'
        DOCKER_IMAGE: quay.io/condaforge/linux-anvil-x86_64:alma9
      linux_64_c_stdlib_version2.28cuda_compiler_version13.0mpiopenmpiscalarreal:
        CONFIG: linux_64_c_stdlib_version2.28cuda_compiler_version13.0mpiopenmpiscalarreal
        UPLOAD_PACKAGES: 'True'
        DOCKER_IMAGE: quay.io/condaforge/linux-anvil-x86_64:alma9
      linux_aarch64_c_stdlib_version2.17cuda_compiler_version12.9mpimpichscalarcomplex:
        CONFIG: linux_aarch64_c_stdlib_version2.17cuda_compiler_version12.9mpimpichscalarcomplex
        UPLOAD_PACKAGES: 'True'
        DOCKER_IMAGE: quay.io/condaforge/linux-anvil-x86_64:alma9
      linux_aarch64_c_stdlib_version2.17cuda_compiler_version12.9mpimpichscalarreal:
        CONFIG: linux_aarch64_c_stdlib_version2.17cuda_compiler_version12.9mpimpichscalarreal
        UPLOAD_PACKAGES: 'True'
        DOCKER_IMAGE: quay.io/condaforge/linux-anvil-x86_64:alma9
      linux_aarch64_c_stdlib_version2.17cuda_compiler_version12.9mpiopenmpiscalarcomplex:
        CONFIG: linux_aarch64_c_stdlib_version2.17cuda_compiler_version12.9mpiopenmpiscalarcomplex
        UPLOAD_PACKAGES: 'True'
        DOCKER_IMAGE: quay.io/condaforge/linux-anvil-x86_64:alma9
      linux_aarch64_c_stdlib_version2.17cuda_compiler_version12.9mpiopenmpiscalarreal:
        CONFIG: linux_aarch64_c_stdlib_version2.17cuda_compiler_version12.9mpiopenmpiscalarreal
        UPLOAD_PACKAGES: 'True'
        DOCKER_IMAGE: quay.io/condaforge/linux-anvil-x86_64:alma9
      linux_aarch64_c_stdlib_version2.17cuda_compiler_versionNonempimpichscalarcomplex:
        CONFIG: linux_aarch64_c_stdlib_version2.17cuda_compiler_versionNonempimpichscalarcomplex
        UPLOAD_PACKAGES: 'True'
        DOCKER_IMAGE: quay.io/condaforge/linux-anvil-x86_64:alma9
      linux_aarch64_c_stdlib_version2.17cuda_compiler_versionNonempimpichscalarreal:
        CONFIG: linux_aarch64_c_stdlib_version2.17cuda_compiler_versionNonempimpichscalarreal
        UPLOAD_PACKAGES: 'True'
        DOCKER_IMAGE: quay.io/condaforge/linux-anvil-x86_64:alma9
      linux_aarch64_c_stdlib_version2.17cuda_compiler_versionNonempiopenmpiscalarcomplex:
        CONFIG: linux_aarch64_c_stdlib_version2.17cuda_compiler_versionNonempiopenmpiscalarcomplex
        UPLOAD_PACKAGES: 'True'
        DOCKER_IMAGE: quay.io/condaforge/linux-anvil-x86_64:alma9
      linux_aarch64_c_stdlib_version2.17cuda_compiler_versionNonempiopenmpiscalarreal:
        CONFIG: linux_aarch64_c_stdlib_version2.17cuda_compiler_versionNonempiopenmpiscalarreal
        UPLOAD_PACKAGES: 'True'
        DOCKER_IMAGE: quay.io/condaforge/linux-anvil-x86_64:alma9
      linux_aarch64_c_stdlib_version2.28cuda_compiler_version13.0mpimpichscalarcomplex:
        CONFIG: linux_aarch64_c_stdlib_version2.28cuda_compiler_version13.0mpimpichscalarcomplex
        UPLOAD_PACKAGES: 'True'
        DOCKER_IMAGE: quay.io/condaforge/linux-anvil-x86_64:alma9
      linux_aarch64_c_stdlib_version2.28cuda_compiler_version13.0mpimpichscalarreal:
        CONFIG: linux_aarch64_c_stdlib_version2.28cuda_compiler_version13.0mpimpichscalarreal
        UPLOAD_PACKAGES: 'True'
        DOCKER_IMAGE: quay.io/condaforge/linux-anvil-x86_64:alma9
      linux_aarch64_c_stdlib_version2.28cuda_compiler_version13.0mpiopenmpiscalarcomplex:
        CONFIG: linux_aarch64_c_stdlib_version2.28cuda_compiler_version13.0mpiopenmpiscalarcomplex
        UPLOAD_PACKAGES: 'True'
        DOCKER_IMAGE: quay.io/condaforge/linux-anvil-x86_64:alma9
      linux_aarch64_c_stdlib_version2.28cuda_compiler_version13.0mpiopenmpiscalarreal:
        CONFIG: linux_aarch64_c_stdlib_version2.28cuda_compiler_version13.0mpiopenmpiscalarreal
        UPLOAD_PACKAGES: 'True'
        DOCKER_IMAGE: quay.io/condaforge/linux-anvil-x86_64:alma9
      linux_ppc64le_mpimpichscalarcomplex:
        CONFIG: linux_ppc64le_mpimpichscalarcomplex
        UPLOAD_PACKAGES: 'True'
        DOCKER_IMAGE: quay.io/condaforge/linux-anvil-x86_64:alma9
      linux_ppc64le_mpimpichscalarreal:
        CONFIG: linux_ppc64le_mpimpichscalarreal
        UPLOAD_PACKAGES: 'True'
        DOCKER_IMAGE: quay.io/condaforge/linux-anvil-x86_64:alma9
      linux_ppc64le_mpiopenmpiscalarcomplex:
        CONFIG: linux_ppc64le_mpiopenmpiscalarcomplex
        UPLOAD_PACKAGES: 'True'
        DOCKER_IMAGE: quay.io/condaforge/linux-anvil-x86_64:alma9
      linux_ppc64le_mpiopenmpiscalarreal:
        CONFIG: linux_ppc64le_mpiopenmpiscalarreal
        UPLOAD_PACKAGES: 'True'
        DOCKER_IMAGE: quay.io/condaforge/linux-anvil-x86_64:alma9
  timeoutInMinutes: 360
  variables: {}

  steps:
  - script: |
         sudo mkdir -p /opt/empty_dir || true
         for d in \
                  /opt/ghc \
                  /opt/hostedtoolcache \
                  /usr/lib/jvm \
                  /usr/local/.ghcup \
                  /usr/local/lib/android \
                  /usr/local/share/powershell \
                  /usr/share/dotnet \
                  /usr/share/swift \
                  ; do
           sudo rsync --stats -a --delete /opt/empty_dir/ $d || true
         done
         sudo apt-get purge -y -f firefox \
                                  google-chrome-stable \
                                  microsoft-edge-stable
         sudo apt-get autoremove -y >& /dev/null
         sudo apt-get autoclean -y >& /dev/null
         df -h
    displayName: Manage disk space
  # configure qemu binfmt-misc running.  This allows us to run docker containers
  # embedded qemu-static
  - script: |
      docker run --rm --privileged multiarch/qemu-user-static:register --reset --credential yes
      ls /proc/sys/fs/binfmt_misc/
    condition: not(startsWith(variables['CONFIG'], 'linux_64'))
    displayName: Configure binfmt_misc

  - script: |
        export CI=azure
        export flow_run_id=azure_$(Build.BuildNumber).$(System.JobAttempt)
        export remote_url=$(Build.Repository.Uri)
        export sha=$(Build.SourceVersion)
        export GIT_BRANCH=$BUILD_SOURCEBRANCHNAME
        export FEEDSTOCK_NAME=$(basename ${BUILD_REPOSITORY_NAME})
        if [[ "${BUILD_REASON:-}" == "PullRequest" ]]; then
          export IS_PR_BUILD="True"
        else
          export IS_PR_BUILD="False"
        fi
        .scripts/run_docker_build.sh
    displayName: Run docker build
    env:
      BINSTAR_TOKEN: $(BINSTAR_TOKEN)
      FEEDSTOCK_TOKEN: $(FEEDSTOCK_TOKEN)
      STAGING_BINSTAR_TOKEN: $(STAGING_BINSTAR_TOKEN)
