# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.
# -*- mode: yaml -*-

jobs:
- job: linux
  pool:
    vmImage: ubuntu-latest
  strategy:
    matrix:
      linux_64_hdf51.10.6=mpi_mpimpichscalarcomplex:
        CONFIG: linux_64_hdf51.10.6=mpi_mpimpichscalarcomplex
        UPLOAD_PACKAGES: 'True'
        DOCKER_IMAGE: quay.io/condaforge/linux-anvil-comp7
      linux_64_hdf51.10.6=mpi_mpimpichscalarreal:
        CONFIG: linux_64_hdf51.10.6=mpi_mpimpichscalarreal
        UPLOAD_PACKAGES: 'True'
        DOCKER_IMAGE: quay.io/condaforge/linux-anvil-comp7
      linux_64_hdf51.10.6=mpi_mpiopenmpiscalarcomplex:
        CONFIG: linux_64_hdf51.10.6=mpi_mpiopenmpiscalarcomplex
        UPLOAD_PACKAGES: 'True'
        DOCKER_IMAGE: quay.io/condaforge/linux-anvil-comp7
      linux_64_hdf51.10.6=mpi_mpiopenmpiscalarreal:
        CONFIG: linux_64_hdf51.10.6=mpi_mpiopenmpiscalarreal
        UPLOAD_PACKAGES: 'True'
        DOCKER_IMAGE: quay.io/condaforge/linux-anvil-comp7
      linux_64_hdf51.12.1mpimpichscalarcomplex:
        CONFIG: linux_64_hdf51.12.1mpimpichscalarcomplex
        UPLOAD_PACKAGES: 'True'
        DOCKER_IMAGE: quay.io/condaforge/linux-anvil-comp7
      linux_64_hdf51.12.1mpimpichscalarreal:
        CONFIG: linux_64_hdf51.12.1mpimpichscalarreal
        UPLOAD_PACKAGES: 'True'
        DOCKER_IMAGE: quay.io/condaforge/linux-anvil-comp7
      linux_64_hdf51.12.1mpiopenmpiscalarcomplex:
        CONFIG: linux_64_hdf51.12.1mpiopenmpiscalarcomplex
        UPLOAD_PACKAGES: 'True'
        DOCKER_IMAGE: quay.io/condaforge/linux-anvil-comp7
      linux_64_hdf51.12.1mpiopenmpiscalarreal:
        CONFIG: linux_64_hdf51.12.1mpiopenmpiscalarreal
        UPLOAD_PACKAGES: 'True'
        DOCKER_IMAGE: quay.io/condaforge/linux-anvil-comp7
  timeoutInMinutes: 360

  steps:
  - script: |
         rm -rf /opt/ghc
         df -h
    displayName: Manage disk space

  # configure qemu binfmt-misc running.  This allows us to run docker containers
  # embedded qemu-static
  - script: |
      docker run --rm --privileged multiarch/qemu-user-static:register --reset --credential yes
      ls /proc/sys/fs/binfmt_misc/
    condition: not(startsWith(variables['CONFIG'], 'linux_64'))
    displayName: Configure binfmt_misc

  - script: |
        export CI=azure
        export GIT_BRANCH=$BUILD_SOURCEBRANCHNAME
        export FEEDSTOCK_NAME=$(basename ${BUILD_REPOSITORY_NAME})
        if [[ "${BUILD_REASON:-}" == "PullRequest" ]]; then
          export IS_PR_BUILD="True"
        else
          export IS_PR_BUILD="False"
        fi
        .scripts/run_docker_build.sh
    displayName: Run docker build
    env:
      BINSTAR_TOKEN: $(BINSTAR_TOKEN)
      FEEDSTOCK_TOKEN: $(FEEDSTOCK_TOKEN)
      STAGING_BINSTAR_TOKEN: $(STAGING_BINSTAR_TOKEN)